### PR TITLE
Revert "feat(backend): added joi validation and error handling, jwt and eslint"

### PR DESCRIPTION
**Pull request by apeksha235**
Reverts jain-rishabh-21/DoctorVerse#71

@madhur87 your pr deleted the changes made in the `routes` file yesterday, please check it!

### CODE REVIEW

**Comment by madhur87** [comment]
@apeksha235, yeh I know I change the Folder Structure, if you look the controller, you got the yesterday changes.

**Comment by madhur87** [comment]
The change is related to JWT.

**Comment by madhur87** [comment]
https://github.com/jain-rishabh-21/DoctorVerse/blob/main/server/controller/user.js#L33

@apeksha235

**Comment by apeksha235** [comment]
Sorry @madhur87 , my bad.

**Pull request closed without merging**
