### PR TITLE
feat(authentication page): authentication page designed

### PR DESCRIPTION
**Pull request by MuzmmilKhan1**

### CODE REVIEW

**Comment by MuzmmilKhan1** [comment]
I don't have access to change the routes.js. So Please maintainers Import the Login From:
`import Login from "./pages/Login/Login";"`

**Comment by apeksha235** [comment]
hey @MuzmmilKhan1 can you change the pr title according to instructions given in contribution.md? thanks

**Comment by MuzmmilKhan1** [comment]
@apeksha235 Could please review it Now I have changed the Title accordingly.

**Comment by MuzmmilKhan1** [comment]
@apeksha235 And please also consider it, whether it is level 2 or level 3 because I was not Improvement in, was complete creation of the page So please consider changing the level.

**Comment by apeksha235** [comment]
Hey @MuzmmilKhan1 sorry but the pr title is still failing, make it all lowercase. 
Also amazing work on the component! appreciate it!

**Comment by MuzmmilKhan1** [comment]
> Hey @MuzmmilKhan1 sorry but the pr title is still failing, make it all lowercase. Also amazing work on the component! appreciate it!

I am glad you liked It, I will try to make better contributions onwards.

**Review by apeksha235 — APPROVED** [review]

**Pull request merged**
