### PR TITLE
feat(backend): added joi validation and error handling, jwt and eslint

### PR DESCRIPTION
**Pull request by madhur87**
In this MR:-> 
1. Implement JWT
2. Joi Validation
3. Error Handling
4. Add User Update Controller
5. Restructure Server Folder'
6. Add ESlint with rules
7. Add ESlint Fix Script in Package.json

Please review and merge this MR @jain-rishabh-21, Thanks #58

### CODE REVIEW

**Comment by MahendraDani** [comment]
@madhur87 Please change the title of PR to something like
`feat(backend): added joi validation and error handling and jwt` to pass the **PR title lint** test case

**Comment by apeksha235** [comment]
Hey @madhur87 could you make the changes specified by @MahendraDani, also there are some merger conflicts I will check it and get back to you!

**Comment by madhur87** [comment]
Okay i made changes.

**Comment by apeksha235** [comment]
@madhur87 can you tell me what all dependencies have you added, since it's showing some merge conflicts in package.json!

**Comment by madhur87** [comment]
Fix everything, and I have add one more this regarding esLint to follow everyone same code format. Please review and MR @apeksha235 @jain-rishabh-21 

@apeksha235 the package.json conflicts for these package joi, eslint, jsonwebtoken

**Comment by madhur87** [comment]
It would be great to add a lint script in the pipeline @jain-rishabh-21

**Comment by apeksha235** [comment]
@madhur87 we had to remove the lint script from the pipeline due to some errors

**Comment by madhur87** [comment]
Yeah, i know that's why I have add only in package file

**Review by apeksha235 — APPROVED** [review]
Good work! @madhur87

**Comment by madhur87** [comment]
Thanks a lot @apeksha235

**Comment by apeksha235** [comment]
hey @madhur87 it seems like you haven't pulled the code after a merge that i did yesterday, can you check it please?

**Comment by madhur87** [comment]
I already pull the latest code and merge that in this branch. @apeksha235

**Pull request merged**
