### PR TITLE
feat(docs): Fixing Image Font in README.md

### PR DESCRIPTION
**Pull request by Swapnil-Singh-99**
## Related Issue

Changed Font in the image of readme file

Closes: #92 

### Describe the changes you've made

I have changed the font of the image in the readme file , so that the text in it properly visible.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement in the existing features
- [x] Other

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] I have verified/tested my code by running it locally.

## Files Added/Modified

- README.md

## Screenshots / Videos / Gif

image

Please merge this PR under GSSOC'23

### CODE REVIEW

**Comment by Swapnil-Singh-99** [comment]
@jain-rishabh-21 Please review and merge it under GSSOC'23

**Comment by Swapnil-Singh-99** [comment]
@jain-rishabh-21 ?

**Comment by jain-rishabh-21** [comment]
@Swapnil-Singh-99 Can you update the PR title to match like the other PRs.

**Comment by Swapnil-Singh-99** [comment]
> @Swapnil-Singh-99 Can you update the PR title to match like the other PRs. 

Done

**Comment by Swapnil-Singh-99** [comment]
@jain-rishabh-21 can you please add a level and a gssoc23 tag

**Comment by jain-rishabh-21** [comment]
Still the title is not correct!

**Comment by Swapnil-Singh-99** [comment]
> Still the title is not correct!

Now is it correct?

**Pull request closed without merging**
