### PR TITLE
feat(backend): adding mvc folder structure 

### PR DESCRIPTION
**Pull request by JainPriya1234**
## Related Issue

 Mvc folder structure added

Closes: [adding MVC folder structure #59 ](https://github.com/jain-rishabh-21/DoctorVerse/issues/59) 

# Describe the changes you've made
I have put all files in proper folder following MVC pattern. The files are imported and exported correctly maintaining their functionality.

 - [ ] Bug fix (non-breaking change which fixes an issue)
- [ ]  New feature (non-breaking change which adds functionality)
 - [x] Enhancement in the existing features
 - [ ] Other
# Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

# Checklist:
 - [x] My code follows the guidelines of this project.
 - [x] I have performed a self-review of my own code.
 - [x] I have commented my code, particularly whereever it was hard to understand.
 - [x] My changes generate no new warnings.
 - [x] I have verified/tested my code by running it locally.
# Files Added/Modified
* models
* router
* controller
* validations
* utlits
* db
## Screenshots / Videos / Gif
image

# Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by JainPriya1234** [comment]
@apeksha235 Please review my PR on issue #59

**Comment by JainPriya1234** [comment]
> hey @JainPriya1234 please change the title of the pr according to the naming convention in `contribution.md` also have you tested this?

yes @apeksha235 I tested it and please let me know now is PR title  correct

**Comment by JainPriya1234** [comment]
@apeksha235 please help me out with pr-title

**Comment by apeksha235** [comment]
@JainPriya1234 you will have to add "feat(backend)" as well like given in the instructions

**Comment by JainPriya1234** [comment]
@apeksha235 please review it

**Comment by JainPriya1234** [comment]
@apeksha235 please review this pr

**Comment by JainPriya1234** [comment]
@apeksha235 please check this PR format as i updated it

**Review by jain-rishabh-21 — APPROVED** [review]

**Comment by jain-rishabh-21** [comment]
@JainPriya1234 Can you resolve the merge conflicts please?

**Comment by JainPriya1234** [comment]
@jain-rishabh-21 I tried to resolve it but someone has done the same work as what is assigned to me that's why it is creating conflicts so I discarded my commits

**Pull request closed without merging**
