### PR TITLE
Added issue template to github directory

### PR DESCRIPTION
**Pull request by f3ve**
## Related Issue

- Create issue template in `.github` directory.

Closes: #7

### Describe the changes you've made

1. Added the file `issue_template.md` to `.github` directory

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement in the existing features
- [x] Other

## Mention any unusual behaviour of your code (Write NA if not)

NA

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] I have verified/tested my code by running it locally.

## Additional Info (optional)

Any additional information you want to give

### CODE REVIEW

**Review by naveen8801 — APPROVED** [review]
Ready to be merged, good work @f3ve ❤️

**Review by jain-rishabh-21 — COMMENTED** [review]
Why is there a change in package-lock.json for this change?

**Comment by naveen8801** [comment]
@f3ve @jain-rishabh-21 This PR will not be counted in GSSOC -22, it was assigned to someone else before.

**Comment by naveen8801** [comment]
@jain-rishabh-21  closing this PR, someone has already worked on it

**Pull request closed without merging**
