### PR TITLE
feat(docs): Fixing Identation errors in ProjectSetup.md

### PR DESCRIPTION
**Pull request by sivasaisilla**
## Fixing Indentation errors
- Changing the indentation fixes in ProjectSetup.md file

Closes: #93 

### Describe the changes you've made

I have added indentation in step 5, so that the two substeps will be under the step number 5.

## Type of change

Documentation Update

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement in the existing features
- [ ] Other

## Mention any unusual behaviour of your code (Write NA if not)

Any unusual behaviour of your code

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] I have verified/tested my code by running it locally.

## Files Added/Modified

- ProjectSetup.md

### CODE REVIEW

**Comment by apeksha235** [comment]
Hey @sivasaisilla can you change the PR title according to the naming convention in contribution.md?

**Comment by sivasaisilla** [comment]
@apeksha235 mam, I have changed PR title according to convention

**Comment by apeksha235** [comment]
hey @sivasaisilla write it as feat(docs)

**Comment by jain-rishabh-21** [comment]
@sivasaisilla Check the title again, see t he other PRs and change it accordingly

**Pull request closed without merging**
