### PR TITLE
feat(backend): added jwt for user signup and login

### PR DESCRIPTION
**Pull request by Deepanshu0703**
## Related Issue

Added jwt token on UserSignUp and UserLogin and will all add the verification of token when the docter related routes are ready

Closes: #45

## Type of change

Added some technologies

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Enhancement in the existing features
- [ ] Other

## Mention any unusual behaviour of your code (Write NA if not)

NaN

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] I have verified/tested my code by running it locally.

## Files Added/Modified

client/package-lock.json
 server/package-lock.json
 server/package.json
 server/routes/user.js

## Screenshots / Videos / Gif
Screenshot (18)

Screenshot (19)

## Additional Info (optional)

I will again raise a issue to secure the routes using jwt token verification when other routes except related to auth will be created.

### CODE REVIEW

**Review by apeksha235 — APPROVED** [review]
Great work! @Deepanshu0703

**Comment by Deepanshu0703** [comment]
Thanks @apeksha235

**Comment by MahendraDani** [comment]
@Deepanshu0703 Please change the PR title to something like
`feat(backend): added jwt for user signup and login` to pass the **PR title lint** test case!

**Comment by Deepanshu0703** [comment]
Thanks @MahendraDani  !!
Changed that .

**Comment by Deepanshu0703** [comment]
Fixes #45

**Comment by Deepanshu0703** [comment]
what about ESLint

**Review by apeksha235 — APPROVED** [review]

**Pull request merged**
