### PR TITLE
Doctor model

### PR DESCRIPTION
**Pull request by ayush25102001**
## Related Issue : #10 

- Initially there was no Doctor model.

Closes: #[10]

### I have added the model folder inside server and inside that I created a doctor.js file which has the doctorSchema of the 
Doctor model. 
I did run the command npm i mongoose(since we are using the mongoose model)

## Type of change

What sort of change have you made: Created a schema for the Doctor model

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Enhancement in the existing features
- [ ] Other

## Mention any unusual behaviour of your code (Write NA if not)  NA

Any unusual behaviour of your code

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] I have verified/tested my code by running it locally.

## Additional Info (optional)

Any additional information you want to give

### CODE REVIEW

**Review by naveen8801 — APPROVED** [review]
Looking good to me 🚀

**Comment by ayush25102001** [comment]
Please review @naveen8801 @jain-rishabh-21

**Comment by ayush25102001** [comment]
Please review @Gurdeep475

**Comment by ayush25102001** [comment]
Please review @naveen8801

**Comment by naveen8801** [comment]
> 

Already done :)

**Comment by ayush25102001** [comment]
> > 
> 
> Already done :)

Then why is it not getting merged

**Comment by ayush25102001** [comment]
@jain-rishabh-21 the PR score is not reflected in the leaderboard ig issue is the Level tag should not have space( Level1)

**Comment by ayush25102001** [comment]
@jain-rishabh-21 sir, the level tag should not have space between Level and 1

**Comment by ayush25102001** [comment]
@naveen8801 sir the tag is incorrect, there should be a space between Level and 1 please update.

**Comment by ayush25102001** [comment]
> @naveen8801 sir the tag is incorrect, there should not be a space between Level and 1 please update.

Please change the label format

**Pull request merged**
